name: tft_cheatsheet_app
description: A Teamfight Tactics information cheatsheet!

version: 2.1.0+22

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+8
  firebase_analytics: ^4.0.2
  flutter_markdown: ^0.2.0
  flutter_typeahead: ^1.6.1
  provider: ^3.0.0+1
  rxdart: ^0.22.0
  super_tooltip: ^0.9.0
  url_launcher: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2

flutter_icons:
  android: true
  image_path: assets/icons/launcher/icon_dark_512.png

flutter:
  uses-material-design: true
  fonts:
    - family: StatIcons
      fonts:
        - asset: assets/fonts/StatIcons.ttf

  assets:
    - assets/data/champions.json
    - assets/data/classes.json
    - assets/data/items.json
    - assets/data/origins.json
    - assets/data/patches/
    - assets/images/
    - assets/sprites/abilities/
    - assets/sprites/champions/
    - assets/sprites/classes/
    - assets/sprites/items/
    - assets/sprites/origins/
    - assets/splash/champions/
